apiVersion: v1
kind: Service
metadata:
  name: {{.Values.db.name}}
  labels:
    app: {{.Values.db.name}}
spec:
  type: {{.Values.db.Servicetype }}
  ports:
    - port: {{ .Values.db.servicePort }}
      targetPort: {{.Values.db.containerPort}}
      protocol: TCP
      name: {{.Values.db.name}}
  selector:
    app: {{.Values.db.name}}
  clusterIP: None